#!/usr/bin/env node
/**
 * coverage-ratchet.js — per-file coverage ratchet against coverage/baseline.json
 *
 * Reads coverage/baseline.json (llvm-cov-shaped baseline committed to the repo)
 * and coverage/current.json (generated by `cargo llvm-cov --json --summary-only`).
 *
 * Baseline schema (coverage/baseline.json):
 *   {
 *     "_meta": { ... },
 *     "files": {
 *       "src/foo.rs": { "lines_total": N, "lines_covered": N, "pct": N }
 *     }
 *   }
 *
 * Current report schema (cargo llvm-cov --json output):
 *   {
 *     "data": [{
 *       "files": [{
 *         "filename": "/absolute/path/to/src/foo.rs",
 *         "summary": {
 *           "lines": { "count": N, "covered": N, "percent": F }
 *         }
 *       }]
 *     }]
 *   }
 *
 * Per-file comparison: fail if current lines.percent < baseline pct.
 * File missing from current -> NOT a violation (deletion is allowed).
 * New files in current not in baseline -> INFO log only.
 *
 * Blast radius: blocks PRs that reduce per-file line coverage below committed baseline.
 * False-positive rate: <1% (line coverage is deterministic for a fixed test suite).
 *
 * Usage:
 *   node ops/checks/coverage-ratchet.js [--help]
 *
 *   Environment overrides (for testing):
 *     COVERAGE_BASELINE_PATH   override path to baseline.json
 *     COVERAGE_CURRENT_PATH    override path to current.json
 *     REPO_ROOT                override repo root for filename relativization
 *
 * Exit codes:
 *   0 — all baseline files meet or exceed their recorded pct (or absent from current)
 *   1 — one or more files dropped below baseline pct
 *   2 — usage/configuration error (missing file, invalid JSON, wrong schema)
 */

"use strict";

const fs = require("node:fs");
const path = require("node:path");

// ── --help ──────────────────────────────────────────────────────────────────

if (process.argv.includes("--help") || process.argv.includes("-h")) {
  console.log(`
coverage-ratchet.js — per-file llvm-cov coverage ratchet

Usage:
  node ops/checks/coverage-ratchet.js [--help]

Reads:
  coverage/baseline.json  — committed per-file baseline (lines_total, lines_covered, pct)
  coverage/current.json   — generated by:
                              cargo llvm-cov --json --output-path coverage/current.json

Environment overrides (for testing fixtures):
  COVERAGE_BASELINE_PATH   path to baseline JSON (default: <repo-root>/coverage/baseline.json)
  COVERAGE_CURRENT_PATH    path to current JSON  (default: <repo-root>/coverage/current.json)
  REPO_ROOT                repo root used to relativize absolute filenames in current.json

Exit codes:
  0  all files at or above baseline, or absent from current (deletion allowed)
  1  one or more files dropped below baseline pct
  2  configuration / parse error
`);
  process.exit(0);
}

// ── Paths ───────────────────────────────────────────────────────────────────

const repoRoot = process.env.REPO_ROOT
  ? path.resolve(process.env.REPO_ROOT)
  : path.resolve(__dirname, "../..");

const baselinePath = process.env.COVERAGE_BASELINE_PATH
  ? path.resolve(process.env.COVERAGE_BASELINE_PATH)
  : path.join(repoRoot, "coverage", "baseline.json");

const currentPath = process.env.COVERAGE_CURRENT_PATH
  ? path.resolve(process.env.COVERAGE_CURRENT_PATH)
  : path.join(repoRoot, "coverage", "current.json");

// ── Load files ───────────────────────────────────────────────────────────────

if (!fs.existsSync(baselinePath)) {
  console.error(`ERROR [coverage-ratchet]: baseline not found: ${baselinePath}`);
  console.error("  The baseline is committed to the repo at coverage/baseline.json.");
  process.exit(2);
}

if (!fs.existsSync(currentPath)) {
  console.error(`ERROR [coverage-ratchet]: current report not found: ${currentPath}`);
  console.error("  Generate it with:");
  console.error(
    "    cargo llvm-cov --json --output-path coverage/current.json",
  );
  process.exit(2);
}

let baselineDoc;
let currentDoc;

try {
  baselineDoc = JSON.parse(fs.readFileSync(baselinePath, "utf8"));
} catch (e) {
  console.error(
    `ERROR [coverage-ratchet]: failed to parse ${baselinePath}: ${e.message}`,
  );
  process.exit(2);
}

try {
  currentDoc = JSON.parse(fs.readFileSync(currentPath, "utf8"));
} catch (e) {
  console.error(
    `ERROR [coverage-ratchet]: failed to parse ${currentPath}: ${e.message}`,
  );
  process.exit(2);
}

// ── Validate baseline schema ─────────────────────────────────────────────────

if (!baselineDoc.files || typeof baselineDoc.files !== "object") {
  console.error(
    `ERROR [coverage-ratchet]: ${baselinePath} must have a top-level "files" object.`,
  );
  console.error(
    '  Expected: { "_meta": {...}, "files": { "src/foo.rs": { "lines_total": N, "lines_covered": N, "pct": N } } }',
  );
  process.exit(2);
}

// ── Validate current report schema ───────────────────────────────────────────
// cargo llvm-cov --json produces:
//   { "data": [{ "files": [...], "totals": {...} }], "type": "...", "version": "..." }

if (
  !currentDoc.data ||
  !Array.isArray(currentDoc.data) ||
  currentDoc.data.length === 0 ||
  !Array.isArray(currentDoc.data[0].files)
) {
  console.error(
    `ERROR [coverage-ratchet]: ${currentPath} does not match the cargo llvm-cov --json schema.`,
  );
  console.error(
    '  Expected: { "data": [{ "files": [{ "filename": "...", "summary": { "lines": {...} } }] }] }',
  );
  console.error(
    "  Generate it with: cargo llvm-cov --json --output-path coverage/current.json",
  );
  process.exit(2);
}

// ── Build lookup: relative-path -> lines.percent from current report ─────────

/**
 * Strip the repo root prefix from an absolute filename so it matches
 * the relative keys stored in baseline.json (e.g. "src/foo.rs").
 */
function relativize(abs) {
  const normalized = path.normalize(abs);
  const root = repoRoot.endsWith(path.sep) ? repoRoot : repoRoot + path.sep;
  if (normalized.startsWith(root)) {
    return normalized.slice(root.length);
  }
  return normalized;
}

/** @type {Map<string, number>} relative-path -> lines.percent */
const currentPct = new Map();

for (const fileEntry of currentDoc.data[0].files) {
  const filename = fileEntry.filename;
  if (!filename) continue;

  const linesData = fileEntry.summary && fileEntry.summary.lines;
  if (!linesData || typeof linesData.percent !== "number") {
    console.warn(
      `WARN [coverage-ratchet]: ${filename} has no summary.lines.percent — skipping`,
    );
    continue;
  }

  const relPath = relativize(filename);
  currentPct.set(relPath, linesData.percent);
}

// ── Ratchet comparison ───────────────────────────────────────────────────────

const baselineFiles = baselineDoc.files;
let failed = false;

for (const [file, baselineCov] of Object.entries(baselineFiles)) {
  if (typeof baselineCov.pct !== "number") {
    console.error(
      `ERROR [coverage-ratchet]: baseline entry "${file}" is missing the "pct" field.`,
    );
    console.error(
      '  Baseline must use llvm-cov shape: { "lines_total": N, "lines_covered": N, "pct": N }',
    );
    process.exit(2);
  }

  if (!currentPct.has(file)) {
    // File absent from current report — deletion is allowed (AC c).
    continue;
  }

  const curr = currentPct.get(file);
  const base = baselineCov.pct;

  // Small epsilon absorbs floating-point rounding between the stored
  // baseline (which records rounded values like 99.5) and the full-
  // precision current value (e.g. 99.54954954954955).
  const EPSILON = 0.05;
  if (curr < base - EPSILON) {
    console.error(`FAIL [coverage-ratchet]: ${file}`);
    console.error(
      `  line coverage dropped: ${base}% (baseline) -> ${curr.toFixed(2)}% (current)`,
    );
    failed = true;
  }
}

// ── New files not yet in baseline ────────────────────────────────────────────

for (const [file, pct] of currentPct.entries()) {
  if (!baselineFiles[file]) {
    console.log(
      `INFO [coverage-ratchet]: new file not in baseline: ${file} (${pct.toFixed(2)}% line coverage) — will be baselined on next main run`,
    );
  }
}

// ── Result ───────────────────────────────────────────────────────────────────

if (failed) {
  console.error(
    "\ncoverage ratchet: FAIL — one or more files dropped below their baseline pct",
  );
  console.error(
    "  Fix the coverage regression or escalate to CTO for a waiver (max 90 days).",
  );
  process.exit(1);
}

console.log(
  "coverage ratchet: OK — all baseline files meet or exceed baseline pct",
);
